Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -22,10 +22,11 @@ jobs:
 
       - name: Install Node.js dependencies
         run: npm install
-        working-directory: ./web # 웹 디렉토리에서 의존성 설치
+        working-directory: ./web
 
       - name: Run Node.js Tests
-        run: npm test
+        run: |
+          npm run test || { echo 'Node.js Tests Failed'; exit 1; }
         working-directory: ./web
 
       - name: Setup Python
@@ -36,8 +37,8 @@ jobs:
       - name: Install Python dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r ./ai/requirements.txt # ai 디렉토리의 requirements.txt에서 의존성 설치
+          pip install -r ./ai/requirements.txt
 
       - name: Run Python Tests
         run: |
-          pytest ./ai # ai 디렉토리에서 테스트 실행
+          pytest ./ai
